#!/bin/sh
# "special" cgi->php redirect for thttpd & php4-cgi
# eg. http:/localhost/php4/test/index.php
#  ==  php4-cgi /home/sysop/devel/www/test/index.php

if [ "$PHP_AUTH_USER" = "" ]; then
  export PHP_AUTH_USER="admin"  ## FIXME:
fi
if [ "$PHP_AUTH_PW" = "" ]; then
  export PHP_AUTH_PW="admin"    ## FIXME:
fi

if [ "$DOCUMENT_ROOT" = "" ]; then
  export DOCUMENT_ROOT=/usr/local/www
fi

if [ "$PATH_TRANSLATED" = "" ]; then
  export PATH_TRANSLATED=${DOCUMENT_ROOT}/index.php
fi

if [ "$SCRIPT_FILENAME" = "" ]; then
  export SCRIPT_FILENAME=${PATH_TRANSLATED}
fi

EXT3=${PATH_TRANSLATED#"${PATH_TRANSLATED%????}"}
EXT4=${PATH_TRANSLATED#"${PATH_TRANSLATED%?????}"}
if [ ! "$EXT3" = ".php" -a ! "$EXT4"= ".php4" ]; then
  printf "Content-Type: "
  file -b -i ${PATH_TRANSLATED}
  echo
  cat ${PATH_TRANSLATED}
else
  exec /usr/bin/php4-cgi
fi
