#!/bin/sh
#
# mthttpd_wrapper - wrapper script for mthttpd on FreeBSD
#
# This goes in /usr/local/sbin.  It backgrounds itself, and then runs
# mthttpd in a loop.  If mthttpd exits then the script restarts it
# automatically.
#
# The -D flag tells thttpd to *not* put itself into the background,
# and the -C flag tells it to get the rest of its configuration from
# the specified config file.

(
    while true ; do
	/usr/local/sbin/mthttpd -D -C /usr/local/www/mthttpd_config
	if [ -f /var/run/nologin ] ; then
	    exit
	fi
	sleep 10
	egrep ' mthttpd[:\[]' /var/log/messages |
	  tail -33 |
	  mail -s "mthttpd on `hostname` restarted" root
    done
) &
